before_script:
  - apt update -y
  - apt -y install rsync
  - 'which ssh-agent || ( apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - chmod 600 $ACHORD_SSH_KEY
  - ssh-add $ACHORD_SSH_KEY
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
stages:
  - deploy-prod
deploy-prod:
  stage: deploy-prod
  tags:
    - node16
  cache:
    key: "node_modules_prod"
    paths:
      - "node_modules"
  only:
    - master
  script:
    - cd frontend/pianosheet/
    - npm install
    - npm run build
    - rsync -avz --del -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./build/ $ACHORD_HOST_CONNECT:$FRONTEND_BUILD_FOLDER_FULLPATH
    - docker-compose restart
