before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get -y install curl dirmngr apt-transport-https lsb-release ca-certificates
  - apt-get install -y nodejs npm
  - apt-get -y install rsync
  - node --version
  - npm --version
  - 'which ssh-agent || ( apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -  
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

stages:
  - deploy-prod

deploy-prod:
  stage: deploy-prod
  only:
    - master
  script:
    # backend
    - ls -a
    - pwd
    - rsync -avz --del --exclude-from='.rsyncignore' -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ $SSH_CONNECT:$BACKEND_FOLDER
    - ls -a
    - pwd
    - ssh $SSH_CONNECT "docker-compose -f /var/www/prod/achord.ru/docker-compose.yml -p achordru restart; exit;"
    # frontend
    - cd frontend/pianosheet/
    - ls
    - pwd
    - npm install
    - npm run build
    - rsync -avz --del -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./build/ $SSH_CONNECT:$BUILD_FOLDER_PROD
