version: "3.7"

services: 
    celery:
        build: .
        command: bash -c "celery -A backend worker -l info -f logs/celery.log & celery -A backend beat -l info"
        volumes: 
            - .:/usr/src/pianosheet
        env_file: .env
        depends_on:
        - web
        - redis_achord
        restart: always

    redis_achord:
        image: redis:5-alpine
        restart: always
    db:
        image: postgres:12
        volumes: 
            - ./docker/postgres/backups/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./pg_data:/db/data
        env_file: .env
        restart: always
    web:
        build: .
        command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput &&
                gunicorn backend.wsgi:application --reload --bind 0.0.0.0:9001 --workers=3 --log-level debug"
        volumes: 
            - .:/usr/src/pianosheet
        ports: 
            - 127.0.0.1:9001:9001
        depends_on: 
            - db
        env_file: .env
        restart: always