version: "3.7"

services: 
    db:
        image: postgres:12
        volumes: 
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./pg_data:/db/data
        env_file: .env
        restart: always
    web:
        build: .
        command: sh -c "cd backend && python manage.py collectstatic --noinput && 
                python manage.py migrate --noinput &&
                gunicorn backend.wsgi:application --reload --bind 0.0.0.0:9001 --workers=3 --log-level debug"

        volumes: 
            - ./backend/:/usr/src/pianosheet/backend
        ports: 
            - 127.0.0.1:9001:9001
        depends_on: 
            - db
        env_file: .env
        restart: always
