# Generated by Django 3.2 on 2021-08-22 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pianosheet.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='имя')),
                ('alias', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='alias')),
                ('info', models.CharField(blank=True, default='', max_length=4000, null=True, verbose_name='информация')),
                ('preview', models.ImageField(blank=True, default='default.png', null=True, upload_to='previews/', verbose_name='превью картинка')),
                ('preview_s', models.ImageField(blank=True, default='default.png', null=True, upload_to='previews_s/', verbose_name='превью картинка')),
                ('preview_xs', models.ImageField(blank=True, default='default.png', null=True, upload_to='previews_xs/', verbose_name='превью картинка')),
                ('rate', models.IntegerField(default=0, verbose_name='рейтинг')),
                ('verificated', models.BooleanField(default=False, verbose_name='проверено')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aвтор',
                'verbose_name_plural': 'aвторы',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='имя')),
                ('filename', models.FileField(default=None, max_length=500, upload_to=pianosheet.functions.PathAndRename('notes'), verbose_name='файл с нотами')),
                ('savedate', models.DateTimeField(auto_now=True, verbose_name='Дата сохранения')),
                ('content_list', models.CharField(blank=True, max_length=2000, null=True, verbose_name='содержание')),
                ('rate', models.IntegerField(default=0, verbose_name='рейтинг')),
                ('verificated', models.BooleanField(default=False, verbose_name='проверено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pianosheet.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'ноты',
                'verbose_name_plural': 'ноты',
            },
        ),
    ]
