# Generated by Django 3.2 on 2021-11-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianosheet', '0003_auto_20211108_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='genres',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='authors', to='pianosheet.Genre', verbose_name='жанры'),
        ),
    ]
