# Generated by Django 3.2 on 2021-11-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianosheet', '0004_alter_author_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='genres',
            field=models.ManyToManyField(related_name='authors', to='pianosheet.Genre', verbose_name='жанры'),
        ),
    ]
