# Generated by Django 3.2 on 2021-12-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianosheet', '0005_alter_author_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='preview',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='genre/preview/', verbose_name='превью картинка'),
        ),
    ]
