# Generated by Django 3.2 on 2022-02-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianosheet', '0007_auto_20220220_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorstat',
            options={'verbose_name': 'Лайки Избранное Авторы', 'verbose_name_plural': 'Лайки Избранное Авторы'},
        ),
        migrations.AlterModelOptions(
            name='notestat',
            options={'verbose_name': 'Лайки Избранное Ноты', 'verbose_name_plural': 'Лайки Избранное Ноты'},
        ),
    ]
